
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 15 23:27:57 PYT 2013
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int DIVIDER = 28;
  public static final int LBRACKET = 37;
  public static final int LPAREN = 32;
  public static final int INT = 11;
  public static final int MINUS = 26;
  public static final int STATIC = 5;
  public static final int RPAREN = 33;
  public static final int NOT = 24;
  public static final int SEMICOLON = 34;
  public static final int AND = 30;
  public static final int LESSTHAN = 31;
  public static final int COMMA = 18;
  public static final int CLASS = 3;
  public static final int PLUS = 25;
  public static final int MAIN = 7;
  public static final int IF = 14;
  public static final int THIS = 22;
  public static final int DOT = 17;
  public static final int EOF = 0;
  public static final int MULTIPLIER = 27;
  public static final int BOOLEAN = 12;
  public static final int RETURN = 9;
  public static final int RBRACKET = 38;
  public static final int TRUE = 20;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int BECOMES = 29;
  public static final int NUMBER = 40;
  public static final int VOID = 6;
  public static final int LBRACE = 35;
  public static final int ELSE = 15;
  public static final int WHILE = 16;
  public static final int PUBLIC = 4;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 8;
  public static final int STRING = 10;
  public static final int FALSE = 21;
  public static final int PRINT = 13;
  public static final int LENGTH = 19;
  public static final int IDENTIFIER = 39;
}

